name = "The Transcontinental Co"
author = "kilaXphantom"
version = "2.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3805a1c4507d41c86118b1ed8d5fdb698de88ff57b1169d54be983344eb827da"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
