name = "The Transcontinental Co"
author = "kilaXphantom"
version = "2.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba4cd16e13c3b7f6eaf938077e5ac5973077e3ee7e39c5d45633a90796960eef"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
