name = "The Transcontinental Co"
author = "kilaXphantom"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4694d0ce570b676bae1a9bc07b9008a3b520a96a4e7b48067f166a949bff72e"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
