
#FollowVoice Config
#Defines how mobs react to player voices, including their movement speed, detection range, and reaction threshold.
[mob_voice_configs]
	mob_configs = ["minecraft:zombie=speed=1.2,range=30,threshold=-40.0", "minecraft:skeleton=speed=1.2,range=30,threshold=-40.0", "minecraft:creeper=speed=1,range=20,threshold=-28.0", "minecraft:spider=speed=1.4,range=30,threshold=-40", "jeg:ghoul=speed=1,range=30,threshold=-40.0"]

#RunawayVoiceGoal Config
#Defines how animals react to player voices, including their fleeing speed, detection range, and reaction threshold.
[animal_voice_configs]
	animal_configs = []

#Whisper Config
#Multipliers that affect the detection range and movement speed when the player is whispering.
[whisper_configs]
	#Range: 0.0 ~ 1.0
	whisper_range_multiplier = 0.25
	#Range: 0.0 ~ 1.0
	whisper_speed_multiplier = 1

#Misc Config
#Multipliers that affect the detection range of voices in specific situations.
[misc_config]
	#Range: 0.0 ~ 1.0
	thunder_range_multiplier = 0.5
	#Range: 0.0 ~ 1.0
	sneaking_range_multiplier = 0.1

#Armor Effects Config
#Define multipliers for mob detection range and speed when a player wears specific armor items.
#Format: item_id=speedMultiplier,rangeMultiplier
#Example: minecraft:diamond_helmet=0.5,0.5
[armor_effects]
	effects = []

#Death Angels Mod Config
#Defines the threshold detection (how hard the player must speak)
#You need this mod for this parameter: https://www.curseforge.com/minecraft/mc-mods/death-angels
[death_angels_config]
	#Range: -127.0 ~ 0.0
	death_angels_threshold = -20.0

